<?php
//tra toan bo group cua user,mang co dang array(group1,group2)

function doji_group_show_group($uid) {
  $nid = db_result(db_query("SELECT nid FROM {content_type_pq_user} WHERE field_gantoi_value = %d",$uid));
  $node = node_load($nid);
  foreach($node-> field_dlieu_gia as $k => $value) {
    $data[] = $value['value'];
  }
  return $data;
}
//Lay tat ca group cua user: bao gom ca nhap tay va khong nhap tay
function  doji_group_getall_group($uid, $nhaptay = null){
  $nid = db_result(db_query("SELECT nid FROM {content_type_pq_user} WHERE field_gantoi_value = %d",$uid));
  $node = node_load($nid);
  if(!isset($nhaptay)) {
    foreach($node-> field_dlieu_gia as $k => $value) {
      $data['group'] = $node->field_dlieu_gia[$k]['value'];
      $data['title'] = $node->field_label[$k]['value'];
      $datas[] = $data;
    }
  }
  else{
    for($i = 0; $i < 5; $i++) {
      $group = $node->field_dlieu_gia[$i]['value'];
      $data['field'] = str_replace('group_','',$group);
      $data['title'] = $node->field_label[$i]['value'];
      $datas[] = $data;
    }
  }
  return $datas;
}
//Get all field cua user neu isset uid, toan bo field neu !isset uid

function doji_group_all_field($uid = null) {
  if(!isset($uid)) {
    $all_group = doji_gold_price_group_options();
    $all_group = array_keys($all_group);
    foreach($all_group as $m => $data) {
      $field = str_replace('group','field',$data);
      $row[] = $field.'_muavao';
      $row[] = $field.'_banra';
      $row[] = $field.'_chenhlech';
    }
  }
  else {
    $nid = db_result(db_query("SELECT nid FROM {content_type_pq_user} WHERE field_gantoi_value = %d",$uid));
    $node = node_load($nid);
    foreach($node-> field_dlieu_gia as $k => $value) {
      $group = $value['value'];
      $field = str_replace('group','field',$group);
      $row[] = $field.'_muavao';
      $row[] = $field.'_banra';
      $row[] = $field.'_chenhlech';
    }
  }
  return $row;
}

//create node bien_do tu dong khi tao user moi

function doji_group_create_node_biendo($uid) {
  $group_uid = variable_get('group_'.$uid,1);
  $group_hn = doji_group_getall_group(1);
  $vung = doji_show_uid_to_vung($uid);
  $node = new StdClass();
  $node -> uid = 1;
  $node->type = 'bien_do';
  $node->language = LANGUAGE_NONE;
  $node->title = 'Biên độ cho '.$vung;
  $node->body[$node->language][0]['format']  = 2;
  for($i = 0; $i < 5; $i ++ ) {
    $node->field_can_thamchieu[$i]['value'] = $group_uid[$i];
    $node->field_gia_chuan[$i]['value'] = $group_hn[$i]['group'];
  }
  $node -> field_gan_user[0]['value'] = $uid;
  node_save($node);
}
//create node phan quyen user co 5 truong ban dau nhap tay khi tao user moi

function doji_group_create_node_pq_user($uid) {
  $group_uid = variable_get('group_'.$uid,1);
  //$group_uid = doji_group_getall_group($uid);
  $group_hn = doji_group_getall_group(1);
  $name = doji_group_return_label($uid);
  $vung = doji_show_uid_to_vung($uid);

  $node = new StdClass();
  $node->type = 'pq_user';
  $node->language = LANGUAGE_NONE;
  $node -> uid = 1;
  $node->title = 'Phân quyền cho '.$vung;
  $node->body[$node->language][0]['format']  = 2;
  for($i = 0; $i < 5; $i ++ ) {
    $node->field_dlieu_gia[$i]['value'] = $group_uid[$i];
    $node->field_label[$i]['value'] = $name[$i];
    $node->field_nhaptay [$i]['value'] = 1;
  }
  $node -> field_gantoi[0]['value'] = $uid;
  node_save($node);
}

//tao node hien thi trang chủ khi tao user vung mien

function doji_group_create_node_show($uid) {
  $group_uid = variable_get('group_'.$uid,1);
  //$group_uid = doji_group_getall_group($uid);
  $group_hn = doji_group_getall_group(1);
  $name = doji_group_return_label($uid);
  $vung = doji_show_uid_to_vung($uid);

  $node = new StdClass();
  $node->type = 'show';
  $node->language = LANGUAGE_NONE;
  $node -> uid = 1;
  $node->title = 'Hiển thị trang chủ '.$vung;
  $node->body[$node->language][0]['format']  = 2;
  for($i = 0; $i < 5; $i ++ ) {
    $node->field_set_select_data[$i]['value'] = $group_uid[$i];
    $node->field_set_label[$i]['value'] = $name[$i];
  }
  $node -> field_set_user[0]['value'] = $uid;
  node_save($node);
}

function doji_group_return_label($uid) {
  $name_vung = doji_show_uid_to_vung($uid);
  $row[] = 'Doji lẻ '.$name_vung;
  $row[] = 'Doji buôn '.$name_vung;
  $row[] = 'Phi JSC '.$name_vung;
  $row[] = 'Nguyên liệu 999 '.$name_vung;
  $row[] = 'Nguyên liệu 9999 '.$name_vung;
  return $row;
}

//add thêm group tới phân quyền khi user vung miền tạo thêm giá mới

function doji_group_add_gia_to_phanquyen($uid,$group) {
  $nid_pq = db_result(db_query("SELECT nid FROM {content_type_pq_user} WHERE field_gantoi_value = %d",$uid));
  $node = node_load($nid_pq);
  $count = count($node-> field_dlieu_gia);
  $node -> field_dlieu_gia[$count]['value'] = $group;
  node_save($node);
}

//lựa chọn thêm group để hiển thị trong phần thiết lập giá

function doji_group_add_thietlap($uid) {
  $nid_ht = db_result(db_query("SELECT nid FROM {content_type_show} WHERE field_set_user_value = %d",$uid));
  $node = node_load($nid_ht);
  $gia = $node -> field_gia_hienthi ;
  $count = count($gia);
  if($count > 0) {
    foreach($gia as $k => $value) {
      $row[] = $value['value'];
    }
  }
  else
    $row = array();
  return $row;
}