<?php
function doji_show_init() {
  drupal_add_js(drupal_get_path('module', 'doji_show') . '/js/doji_show.js');
  drupal_add_js(drupal_get_path('module', 'doji_show') . '/js/jquery.bpopup.min.js');
}

function doji_show_menu() {
  $items['doji/admin/biendo'] = array(
    'title' => t('Thiết lập biên độ', array(), 'vi'),
    'page callback' => 'doji_show_setting_biendo',
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 7,
  );
  $items['doji/admin/phanquyen'] = array(
    'title' => t('Phân quyền user', array(), 'vi'),
    'page callback' => 'doji_show_phanquyen_user',
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 8,
  );
  return $items;
}

function doji_show_phanquyen_user() {
  drupal_set_title('');
  $form  = drupal_get_form('doji_show_select_vung');
  $uid = $_GET['area'];
  $nid_pq = db_result(db_query("SELECT nid FROM {content_type_pq_user} WHERE field_gantoi_value = %d",$uid));
  module_load_include('inc', 'node', 'node.pages');
  $node = node_load($nid_pq);
  $output = node_page_edit($node);
  $output = '<div id="doji_set" class="hidden">' . $output . '</div>';
  $output = $form.$output;
  return $output;
}
function doji_show_setting_biendo() {
  drupal_set_title('');
  $form  = drupal_get_form('doji_show_select_vung');
  $uid = $_GET['area'];
  $nid_bd = db_result(db_query("SELECT nid FROM {content_type_bien_do} WHERE field_gan_user_value = %d",$uid));

  module_load_include('inc', 'node', 'node.pages');
  $node = node_load($nid_bd);
  $output = node_page_edit($node);
  $output = '<div id="doji_set" class="hidden">' . $output . '</div>';
  $output = $form.$output;
  return $output;
}


function doji_user_setting_id_hienthi() {
  $query = db_query("SELECT field_set_user_value as uid FROM {content_type_user_setting}");
  while($row = db_fetch_array($query)) {
    $data[] = $row['uid'];
  }
  return $data;
}

function doji_show_gia_vang($uid = null) {
  if(!isset($uid)) {
    $user = doji_add_user_get();
  }
  else {
    $user = array($uid => 'macdinh');
  }
  $output = '';
  foreach($user as $uid => $giatri) {
    $nid_node_show = db_result(db_query('SELECT nid from {content_type_show} WHERE field_set_user_value = %d',$uid));
    $all_field = doji_show_get_allfield_from_nid($nid_node_show);
    $data_path_details = doji_get_data_path_details();
    $data_path_details['filepath'] = $data_path_details['path'] . '/'  . $data_path_details['prefix'] .  '_vungmien_' . $uid . '.dat';
    $output = file_get_contents($data_path_details['filepath']);
    if (empty($output) || !$output) {
      $node = doji_get_node('last', 'goldprice');
      $node1 = node_load($nid_node_show);

      foreach ($node1->field_set_select_data as $k => $v) {
        $m = $node1->{field_set_select_data}[$k]['value'];
        $group_access[$m] = NULL;
        if (isset($node1->field_set_label[$k]['value']) && $node1->field_set_label[$k]['value']) {
          $group_access[$node1->field_set_select_data[$k]['value']]['label'] =  $node1->field_set_label[$k]['value'];
        }
      }
      if (count($group_access)) {
        $output .= '<h2 class="title_bang"> Bảng giá tại '.doji_show_uid_to_vung($uid).'</h2>';
        $output .= theme('doji_goldprice_view_1', $node, NULL, NULL, $group_access);
      }
      else {
        $output = t('Hiện không có dữ liệu phù hợp', array(), 'vi');
      }
      file_save_data($output, $data_path_details['filepath'], FILE_EXISTS_REPLACE);
    }
  }
  return $output;
}

function doji_show_get_allfield_from_nid($nid) {
  $query = db_query("SELECT field_set_select_data_value as group_name FROM {content_field_set_select_data} WHERE nid = %d",$nid);
  while($row= db_fetch_array($query)) {
    $data[] = $row['group_name'];
  }
  $rows = array();
  foreach($data as $k => $value) {
    $field = str_replace('group','field',$value);
    $mua_vao = $field.'_muavao';
    $ban_ra =  $field.'_banra';
    $rows[] = $mua_vao;
    $rows[] = $ban_ra;
  }
  return $rows;
}

function doji_show_select_vung($form, &$form_state) {
  if(isset($_GET['area'])) {
    $vung = $_GET['area'];
  }
  $user = doji_show_uid_and_vung();
  $user =  array('' => '--Chọn vùng miền--') + $user;
  $form = array();
  $form['area'] = array(
    '#type' => 'select',
    '#title' => '',
    '#default_value' => $vung,
    '#options' => $user,
  );
  if(arg(1) =='admin') {
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Tìm kiếm',
    );
  }

  return $form;
}

function doji_show_select_vung_validate($form, &$form_stat){

}

function doji_show_select_vung_submit($form, &$form_state){
  $area = $form_state['values']['area'];
  if(arg(2) =='biendo') {
    $form_state['redirect'] = array(
      'doji/admin/biendo',
      array(
        'area' => $area,
      ),
    );
  }
  if(arg(2) == 'phanquyen') {
    $form_state['redirect'] = array(
      'doji/admin/phanquyen',
      array(
        'area' => $area,
      ),
    );
  }

}
/**
 * implement hook_block
 */

function doji_show_block($op = 'list', $delta = 0, $edit = array()) {
  switch($op) {
    case 'list':
      $blocks = array();
      $blocks['setting_biendo']['info'] = t('Thiết lập biên độ', array(), 'vi');
      $blocks['show_bdo']['info'] = t('Hiển thị biên độ', array(), 'vi');
      return $blocks;
    case 'view' :
      $blocks = array();
      switch ($delta) {
        case 'setting_biendo' :
          $blocks['subject'] = 'Thiết lập biên độ';
          $blocks['content'] = doji_show_block_biendo();
          break;
        case 'show_bdo' :
          $blocks['subject'] = 'Hiển thị biên độ';
          $blocks['content'] = doji_show_biendo();
          break;
      }
      return $blocks;
  }
}

function doji_show_block_biendo() {
  global $user;
  module_load_include('inc', 'node', 'node.pages');
  $node = node_load(45748);
  $form = node_page_edit($node);
  $form = '<div class="clear-form goldprice-sxht">' . $form . '</div>';
  return $form;
}

function doji_show_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  $uid = $user -> uid;
  if($form_id == 'bien_do_node_form') {
   unset($form['title']);
   unset($form['body_field']);
  }
  if($uid == 1) {
    if($form_id == 'user_register') {
      $form['submit']['#suffix'] = doji_show_popup();
    }
  }
}

function doji_show_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
 if($node -> type == 'bien_do') {
   if($op == 'update') {
     drupal_goto('<front>');
   }
 }
}

//Thiệp lập hiển thị biên độ: phần hiển thị ra trang chu user

function doji_show_biendo() {
  global $user;
  $uid = $user -> uid;
  $data = doji_add_user_get_data($uid);
  if($uid == 1) {
    $data = doji_add_user_get_data($uid,1);
  }
  $node_bd = doji_get_node('last');
}

/*
 * Implement hook_user
 */

function doji_show_user($op, &$edit, &$account, $category = NULL) {
  global $user;
  $uid_t = $user -> uid;
  if($uid_t == 1) {
    switch($op) {
      case 'insert':
        $uid = $account -> uid;
        if(isset($edit['roles'][3])) {
          $row['uid'] = $account -> uid;
          if(empty($edit['vung_mien']))
            $row['vung_mien'] = '';
          else
            $row['vung_mien'] = $edit['vung_mien'];
          drupal_write_record("doji_group_vung",$row);
          //tao them 5 gia
          doji_add_user_add_group($edit['vung_mien'],$uid);
          //Tao node phan quyen
          doji_group_create_node_pq_user($uid);
          // tạo node bien do
          doji_group_create_node_biendo($uid);

        }

        break;
      case 'update':
        $vung_mien = $edit['vung_mien'];
        $uid = $account -> uid;
        $result = db_result(db_query('SELECT uid FROM {doji_group_vung} WHERE uid = %d',$account ->uid));
        if($result){
          db_query('UPDATE {doji_group_vung} SET vung_mien = "%s" WHERE uid = %d',$vung_mien,$uid);
        }
        else{
          $row['uid'] = $account -> uid;
          if(empty($edit['vung_mien']))
            $row['vung_mien'] = '';
          else
            $row['vung_mien'] = $edit['vung_mien'];
          drupal_write_record("doji_group_vung",$row);
        }
      case 'register':
        $form['vung_mien'] = array(
          '#type' => 'textfield',
          '#title' => t('Vùng miền')
        );
        return $form;
        break;
      case 'form':
        $value = db_result(db_query('SELECT vung_mien FROM {doji_group_vung} WHERE uid = %d',$account -> uid));
        $form['vung_mien'] = array(
          '#type' => 'textfield',
          '#title' => t('Vùng miền'),
          '#default_value' => $value?$value:''
        );
        return $form;
        break;
    }
  }
}

//tra ve array gom uid va ten vung mien

function doji_show_uid_and_vung($uid = null) {
  if(!isset($uid)) {
    $query = db_query("SELECT uid,vung_mien FROM {doji_group_vung}");
  }
  else {
    $query = db_query("SELECT uid,vung_mien FROM {doji_group_vung} WHERE uid = %d",$uid);
  }
  while($row = db_fetch_array($query)) {
    $rows[$row['uid']] = $row['vung_mien'];
  }
  return $rows;
}
//Truyen vao uid tra ve ten vung mien
function doji_show_uid_to_vung($uid) {
  $query = db_result(db_query("SELECT vung_mien FROM {doji_group_vung} WHERE uid = %d",$uid));
  return $query;
}

// hiển thị trang quantri.html
function doji_show_quantri() {
  drupal_set_title('');
  global $user;
  if($user -> uid ==1) {
    $query = db_query("SELECT user.uid as uid,user.name as name, vung.vung_mien as vung FROM {users} as user INNER JOIN {doji_group_vung} vung ON user.uid = vung.uid");
  }
  else {
    $query = db_query("SELECT user.uid as uid,user.name as name, vung.vung_mien as vung FROM {users} as user INNER JOIN {doji_group_vung} vung ON user.uid = vung.uid AND vung.uid = %d",$user -> uid);
  }

  $i = 0;
  while($row= db_fetch_array($query)) {
    $i++;
    $data['tt'] = $i;
    $data['name'] = $row['name'];
    $data['qt'] = t('Quản trị');
    $data['vung'] = $row['vung'];
    $data['biendo'] = '<a href ="doji/admin/biendo?area='.$row['uid'].'">Thiết lập</a>';
    $data['pq'] = '<a href ="doji/admin/phanquyen?area='.$row['uid'].'">Phân quyền</a>';
    $data['edit'] = '<a href ="user/'.$row['uid'].'/edit?destination=doji/admin">Sửa</a>';
    $data['delete'] = '<a href ="user/logout">Thoát</a>';
    if($user ->uid == 1)
      $data['delete'] = '<a href ="user/'.$row['uid'].'/delete?destination=doji/admin">Xóa</a>';
    $datas[] = $data;
  }
  $header = array("Thứ tự",'Tên đăng nhập', 'Vai trò','Vùng miền','Thiết lập biên độ','Sửa', 'Thoát');
  if($user -> uid == 1)
    $header = array("Thứ tự",'Tên đăng nhập', 'Vai trò','Vùng miền','Thiết lập biên độ','Phân quyền','Sửa', 'Xóa');
  $output = theme('table', $header, $datas, array('class' => 'user_qt'));
  $output .= '<div class="add_u"><a href="admin/user/user/create?destination=doji/admin"> Thêm quản trị mới</a></div>';
  return $output;

}
function doji_show_popup() {
  $output = '<div id ="noitce-message"><img src="/sites/all/themes/doji_gold/images/loading-big.gif"><p>Hệ thống đang thiết lập tự động, bạn vui lòng chờ trong vài phút!</p></div>';
  return $output;
}
